import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF754B9D),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF2C0052),
  onPrimaryContainer: Color(0xFF2C0052),
  secondary: Color(0xFFAB3300),
  onSecondary: Color(0xFFFFFFFF),
  onSecondaryContainer: Color(0xFF1D192B),
  tertiary: Color(0xFF7C5800),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFD8E4),
  onTertiaryContainer: Color(0xFFFFDE9F),
  error: Color(0xFFBA1B1B),
  errorContainer: Color(0xFFFFDAD4),
  onErrorContainer: Color(0xFF410001),
  onError: Color(0xFFFFDAD4),
  background: Color(0xFFFBFDFD),
  onBackground: Color(0xFF191C1D),
  surface: Color(0xFFFFFBFE),
  onSurface: Color(0xFF1C1B1F),
  // surfaceVariant: Color(0xFFE9DFEB),
  surfaceVariant: Color(0xFFF0F0F0),
  secondaryContainer: Color(0xFFE9DFEB),
  onSurfaceVariant: Color(0xFF49454F),
  outline: Color(0xFF7C757F),
  onInverseSurface: Color(0xFFF4EFF4),
  inverseSurface: Color(0xFF313033),
  inversePrimary: Color(0xFFD0BCFF),
  shadow: Color(0xFF000000),
);
